[build]
publish = "public"
functions = "netlify/functions"

[[redirects]]
from = "/"
to = "/insights"
status = 301

[[redirects]]
from = "/insights"
to = "/.netlify/functions/insights"
status = 200

[[redirects]]
from = "/insights/"
to = "/.netlify/functions/insights"
status = 200

[[redirects]]
from = "/insights/*"
to = "/.netlify/functions/article?slug=:splat"
status = 200
force = true
